name: Validate Exercises (Multi-Platform)

on:
  push:
    paths:
      - 'snippets/**'
      - '.github/workflows/validate_exercises.yml'
  pull_request:
    paths:
      - 'snippets/**'
      - '.github/workflows/validate_exercises.yml'

jobs:
  build-and-test:
    name: Build & Test on multiple OS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies (Ubuntu)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3 python3-pip

      - name: Install dependencies (macOS)
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew update
          brew install python
          # brew install gcc (si besoin)

      - name: Install dependencies (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          choco install python --version=3.10.11 -y
          # ou utiliser actions/setup-python (recommandé)
      
      - name: Setup Python (all OS)
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python packages
        run: |
          pip install --upgrade pip
          # pip install pytest si vous avez des tests unitaires

      - name: Compile & Run C (Linux/macOS)
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          bash scripts/compile_run_c.sh
        shell: bash

      - name: Compile & Run C (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          powershell scripts\compile_run_c_windows.ps1
        shell: pwsh

      - name: Test Python
        run: |
          bash scripts/test_python.sh

      - name: Generate summary
        run: |
          # On insère la variable d'environnement GitHub Actions dans la chaîne
          echo "## Résultats de la compilation et exécution (${{ matrix.os }})" >> $GITHUB_STEP_SUMMARY
          
          echo "| Fichier | Statut |" >> $GITHUB_STEP_SUMMARY
          echo "|---------|--------|" >> $GITHUB_STEP_SUMMARY

          # Récap C
          if [ -f results_c.csv ]; then
            tail -n +2 results_c.csv | while IFS=, read -r file status; do
              echo "| \`$file\` | $status |" >> $GITHUB_STEP_SUMMARY
            done
          fi

          # Récap Python
          if [ -f results_python.csv ]; then
            tail -n +2 results_python.csv | while IFS=, read -r file status; do
              echo "| \`$file\` | $status |" >> $GITHUB_STEP_SUMMARY
            done
          fi
