name: Validate Exercises (Multi-Platform)

on:
  push:
    paths:
      - 'snippets/**'
      - '.github/workflows/validate_exercises.yml'
  pull_request:
    paths:
      - 'snippets/**'
      - '.github/workflows/validate_exercises.yml'

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies (Ubuntu)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3 python3-pip

      - name: Install dependencies (macOS)
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew update
          brew install python
          # brew install gcc

      - name: Install dependencies (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          choco install python --version=3.10.11 -y
          choco install mingw -y
          echo "C:\\tools\\mingw64\\bin" >> $GITHUB_PATH

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python packages
        run: |
          pip install --upgrade pip

      - name: Compile & Run C (Linux/macOS)
        if: ${{ matrix.os != 'windows-latest' }}
        run: bash scripts/compile_run_c.sh
        shell: bash

      - name: Allow PS script execution
        if: ${{ matrix.os == 'windows-latest' }}
        run: Set-ExecutionPolicy Bypass -Scope Process
        shell: pwsh

      - name: Compile & Run C (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        # On autorise l'étape à échouer sans stopper le workflow :
        continue-on-error: true
        run: |
          .\scripts\compile_run_c_windows.ps1
        shell: pwsh

      - name: Test Python
        # Python ne devrait pas bloquer la suite, mais on peut faire de même
        continue-on-error: true
        run: |
          bash scripts/test_python.sh

      - name: Generate summary (always)
        if: always()  # s’exécute même si les étapes précédentes ont échoué
        run: |
          echo "## Résultats de la compilation et exécution (${{ matrix.os }})" >> $GITHUB_STEP_SUMMARY
          echo "| Fichier | Statut |" >> $GITHUB_STEP_SUMMARY
          echo "|---------|--------|" >> $GITHUB_STEP_SUMMARY

          if [ -f results_c.csv ]; then
            echo "==> Found results_c.csv"
            tail -n +2 results_c.csv | while IFS=, read -r file status; do
              echo "| \`$file\` | $status |" >> $GITHUB_STEP_SUMMARY
            done
          else
            echo "No results_c.csv found for C" >> $GITHUB_STEP_SUMMARY
          fi

          if [ -f results_python.csv ]; then
            echo "==> Found results_python.csv"
            tail -n +2 results_python.csv | while IFS=, read -r file status; do
              echo "| \`$file\` | $status |" >> $GITHUB_STEP_SUMMARY
            done
          else
            echo "No results_python.csv found for Python" >> $GITHUB_STEP_SUMMARY
          fi
