name: Validate Student Snippets

on:
  push:
    paths:
      - 'snippets/**'
      - '.github/workflows/validate_snippets.yml'
  pull_request:
    paths:
      - 'snippets/**'
      - '.github/workflows/validate_snippets.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # On peut tester aussi sur Windows/macos si on veut

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3 python3-pip

      - name: Compile and run C
        run: |
          bash scripts/compile_run_c.sh
        shell: bash

      - name: Test Python
        run: |
          bash scripts/test_python.sh
        shell: bash

      # (Optionnel) Lancer la comparaison sortie snippet vs solution
      - name: Compare solutions (optionnel)
        run: |
          bash scripts/compare_solutions.sh
        shell: bash

      - name: Generate summary
        run: |
          echo "## Résultats de la compilation" >> $GITHUB_STEP_SUMMARY
          echo "| Langage | Fichier | Statut |" >> $GITHUB_STEP_SUMMARY
          echo "|---------|--------|--------|" >> $GITHUB_STEP_SUMMARY

          # Pour C
          if [ -f results_c.csv ]; then
            tail -n +2 results_c.csv | while IFS=, read -r file status; do
              echo "| C | \`$file\` | $status |" >> $GITHUB_STEP_SUMMARY
            done
          fi

          # Pour Python
          if [ -f results_python.csv ]; then
            tail -n +2 results_python.csv | while IFS=, read -r file status; do
              echo "| Python | \`$file\` | $status |" >> $GITHUB_STEP_SUMMARY
            done
          fi
